services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - database
        container_name: cloudfull_app

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - app
        container_name: cloudfull_nginx

    database:
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: database_dev
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        container_name: cloudfull_database

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8000:80"
        environment:
            - PMA_ARBITRARY=1
